// <auto-generated />
using ExamWeb_LeHoangHuan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamWeb_LeHoangHuan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamWeb_LeHoangHuan.Models.DiaNhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<string>("NgheSi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrongNuoc")
                        .HasColumnType("bit");

                    b.Property<string>("TuaCD")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("DiaNhacs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GiaBan = 100000.0,
                            NgheSi = "Aki",
                            SoLuong = 50,
                            TrongNuoc = true,
                            TuaCD = "No Internet"
                        },
                        new
                        {
                            Id = 2,
                            GiaBan = 120000.0,
                            NgheSi = "jaigon",
                            SoLuong = 40,
                            TrongNuoc = true,
                            TuaCD = "Là Tất Cả"
                        },
                        new
                        {
                            Id = 3,
                            GiaBan = 100000.0,
                            NgheSi = "Sơn Tùng",
                            SoLuong = 20,
                            TrongNuoc = true,
                            TuaCD = "nắng ấm"
                        },
                        new
                        {
                            Id = 4,
                            GiaBan = 100000.0,
                            NgheSi = "Dế Choắt",
                            SoLuong = 10,
                            TrongNuoc = true,
                            TuaCD = "Chú Ché Loắt Choắt"
                        },
                        new
                        {
                            Id = 5,
                            GiaBan = 100000.0,
                            NgheSi = "Bray",
                            SoLuong = 15,
                            TrongNuoc = false,
                            TuaCD = "Để Ai Cần"
                        },
                        new
                        {
                            Id = 6,
                            GiaBan = 100000.0,
                            NgheSi = "Aki",
                            SoLuong = 24,
                            TrongNuoc = true,
                            TuaCD = "Yêu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
